services:
  db-mongo:
    # Version of mongoDB currently in production
    image: mongo:4.2.23
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - db-mongo:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.runCommand({ connectionStatus: 1 })'"]
      interval: 5s
      timeout: 5s
      retries: 5
  db-postgres:
    build:
      dockerfile: docker-resources/postgres/Dockerfile.dev
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_ROOT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_BAN_USER=${POSTGRES_BAN_USER}
      - POSTGRES_BAN_PASSWORD=${POSTGRES_BAN_PASSWORD}
    volumes:
      - db-postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    # Version of Redis currently in production
    image: redis:4.0.9
    ports:
      - "${REDIS_PORT:-6379}:6379"
  minio:
    image: minio/minio
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${MINIO_FRONT_PORT:-90001}:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
  api:
    build:
      dockerfile: docker-resources/api/Dockerfile.dev
    depends_on:
      db-mongo: 
        condition: service_healthy
      db-postgres:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - MONGODB_URL=mongodb://db-mongo
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - POSTGRES_URL=db-postgres
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_ROOT_USER=${POSTGRES_ROOT_USER}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_BAN_USER=${POSTGRES_BAN_USER}
      - POSTGRES_BAN_PASSWORD=${POSTGRES_BAN_PASSWORD}
      - REDIS_URL=redis://redis
      - FANTOIR_PATH=${FANTOIR_PATH}
      - GAZETTEER_DB_PATH=${GAZETTEER_DB_PATH}
      - CONTOURS_DATA_PATH=${CONTOURS_DATA_PATH}
      - COMMUNES_LOCAUX_ADRESSES_DATA_PATH=${COMMUNES_LOCAUX_ADRESSES_DATA_PATH}
      - DEPARTEMENTS=${DEPARTEMENTS}
      - MAX_CONCURRENT_WORKERS=${MAX_CONCURRENT_WORKERS}
      - DATAGOUV_API_KEY=${DATAGOUV_API_KEY}
      - API_DEPOT_URL=${API_DEPOT_URL}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - BAN_API_AUTHORIZED_TOKENS=${BAN_API_AUTHORIZED_TOKENS}
      - BAN_API_URL=${BAN_API_URL}
      - API_IDFIX_URL=${API_IDFIX_URL}
      - API_IDFIX_TOKEN=${API_IDFIX_TOKEN}
      - JOB_STATUS_LIMIT_DURATION=${JOB_STATUS_LIMIT_DURATION}
      - MATOMO_URL=${MATOMO_URL}
      - MATOMO_SITE_ID=${MATOMO_SITE_ID}
      - MATOMO_TOKEN_AUTH=${MATOMO_TOKEN_AUTH}
      - FORCE_DOWNLOAD_CONTOUR=
      - FORCE_DOWNLOAD_DATASETS=
      - S3_REGION={S3_REGION}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ENDPOINT_URL=http://minio:9000
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - data:/app/data
      - dist:/app/dist
      - ./lib:/app/lib
      - ./scripts:/app/scripts
      - ./server.js:/app/server.js
      - ./worker.js:/app/worker.js
      - ./toolbox.dev:/app/toolbox.dev
volumes:
  data:
  dist:
  db-mongo:
  db-postgres:
  minio-data:
