services:
  db-mongo:
    # Version of mongoDB currently in production
    image: mongo:4.2.23
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - db-mongo:/data/db
  db-postgres:
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - db-postgres:/var/lib/postgresql/data
  redis:
    # Version of Redis currently in production
    image: redis:4.0.9
    ports:
      - "${REDIS_PORT:-6379}:6379"
  api:
    build: 
      dockerfile: 'Dockerfile.dev'
    depends_on:
      - db-mongo
      - db-postgres
      - redis
    environment:
      - MONGODB_URL=mongodb://db-mongo
      - MONGODB_DBNAME=${MONGODB_DBNAME}
      - POSTGRES_URL=db-postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - REDIS_URL=redis://redis
      - FANTOIR_PATH=${FANTOIR_PATH}
      - GAZETTEER_DB_PATH=${GAZETTEER_DB_PATH}
      - CONTOURS_DATA_PATH=${CONTOURS_DATA_PATH}
      - COMMUNES_LOCAUX_ADRESSES_DATA_PATH=${COMMUNES_LOCAUX_ADRESSES_DATA_PATH}
      - DEPARTEMENTS=${DEPARTEMENTS}
      - MAX_CONCURRENT_WORKERS=${MAX_CONCURRENT_WORKERS}
      - DATAGOUV_API_KEY=${DATAGOUV_API_KEY}
      - API_DEPOT_URL=${API_DEPOT_URL}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - BAN_API_AUTHORIZED_TOKENS=${BAN_API_AUTHORIZED_TOKENS}
      - BAN_API_URL=${BAN_API_URL}
      - API_IDFIX_URL=${API_IDFIX_URL}
      - API_IDFIX_TOKEN=${API_IDFIX_TOKEN}
      - JOB_STATUS_LIMIT_DURATION=${JOB_STATUS_LIMIT_DURATION}
      - FORCE_DOWNLOAD_CONTOUR=
      - FORCE_DOWNLOAD_DATASETS=
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - data:/app/data
      - dist:/app/dist
      - ./lib:/app/lib
      - ./scripts:/app/scripts
      - ./server.js:/app/server.js
      - ./worker.js:/app/worker.js
      - ./toolbox.dev:/app/toolbox.dev
volumes:
  data:
  dist:
  db-mongo:
  db-postgres: