# Use the official PostgreSQL image as the base image
FROM postgres:16

# Install PostGIS extension
RUN apt-get update && apt-get install -y postgresql-16-postgis-3

# Copy a script to activate PostGIS
COPY docker-resources/postgres/init-postgis.sh /docker-entrypoint-initdb.d